### ISSUE TITLE
[질문] 16.LearnVertexArray 쳅터 glBindVertexArray 함수 질문드립니다.

### ISSUE THREAD

**Issue by sejinpark12** [GraphicsKorea/OpenGLES#2]
안녕하세요. 대명님.

58번 줄에서 glGenVertexArrays 함수로 버텍스 어레이를 생성한 다음에
59번 줄에서 glBindVertexArray 함수로 윗줄에서 생성한 app.vertex_array을 바인드해야 될 것 같은데 app.vertex_buffer를 바인드하도록 되어있는데 현재 코드와 같이 버텍스 버퍼의 네임을 바인드해도 되는 것인지 궁금합니다.

https://github.com/GraphicsKorea/OpenGLES/blob/f3b703b6435eb6b05f33f0e4dee5aa440566b8b1/16.LearnVertexArray/src/main.cpp#L58-L59

감사합니다.

**Comment by daemyung** [comment]
맞습니다. 이 버그는 [6a322488f5b55149f146c40a33f8ed1012335e81](https://github.com/GraphicsKorea/OpenGLES/commit/6a322488f5b55149f146c40a33f8ed1012335e81)로 수정되었습니다.

**Comment by sejinpark12** [comment]
https://github.com/GraphicsKorea/OpenGLES/blob/48606322e8b6d74a8188d18068174373964b187d/17.LearnTexture/src/main.cpp#L60-L61

17.LearnTexture의 main.cpp에도 동일한 코드가 있습니다.

추가 질문입니다.
수정되기 전 코드인 glBindVertexArray(app.vertex_buffer)를 실행하여 버텍스 어레이에 app.vertex_buffer를 바인드하도록 했을 경우에도 출력 화면에 어떻게 사각형이 정상적으로 그려지는 것인지 아니면 정상인 것처럼만 보이는 건지 궁금합니다.
제 생각으로는 버텍스 어레이에 올바른 네임이 바인딩 되지 않았을 경우는 사각형의 스테이트들이 버텍스 어레이에  저장되지 않을 것 같은데 
어떻게 렌더 이벤트에서 아래와 같이 처음 바인딩 되는 app.vertex_array의 정보를 불러와 glDrawElements 함수가 사각형을 그릴 수 있는 걸까요?

https://github.com/GraphicsKorea/OpenGLES/blob/48606322e8b6d74a8188d18068174373964b187d/16.LearnVertexArray/src/main.cpp#L81-L82

바쁘신 와중에도 친절한 답변 늘 감사합니다!

**Comment by daemyung** [comment]
정상적으로 그려지는 이유는 OpenGL ES 스펙과 운이 따랐기 때문입니다. glCreateXXX()를 호출할 때 핸들이 반환되는데, 이 핸들은 1부터 차례대로 증가합니다. 예제의 경우 버텍스 어레이와 버텍스 버퍼의 핸들이 모두 1이기 때문에 정상적으로 동작하는 것처럼 보이게 됩니다.

**Comment by sejinpark12** [comment]
![image](https://user-images.githubusercontent.com/19530862/141938501-d0a926a5-2e24-453f-9b9e-99edb4ddca1f.png)

그렇군요. 감사합니다ㅎ
