### ISSUE TITLE
[질문] 17.LearnTexture 쳅터 텍스처 래핑 질문드립니다.

### ISSUE THREAD

**Issue by sejinpark12** [GraphicsKorea/OpenGLES#3]
안녕하세요. 대명님.

17.LearnTexture 쳅터를 공부하다가 궁금한 점이 생겨서 질문드립니다.

강의의 코드로 프로그램을 실행하면 아래 이미지1과 같이 위쪽과 오른쪽에 텍스처가 반복되고 있는 것처럼 보입니다. 그리고자 하는 사각형 도형의 텍스처 좌표는 각 버텍스에서 올바르게 지정되어 있는 것 같은데 어떤 이유로 텍스처가 사각형 도형에 딱 맞게 입혀지지 않는 것인지 궁금합니다. 텍스처의 크기가 2x2 픽셀로 너무 작아서 그런것 같아 텍스처의 크기를  4x4와 8x8 크기로 설정하고 프로그램을 실행하였더니 이미지2와 이미지3의 결과를 확인할  수 있었습니다. 4x4 픽셀에서는 사각형의 오른쪽에서만 텍스처가 반복되고 8x8 픽셀에서는 위쪽 오른쪽 모두 정상적으로 그려졌습니다.

![image](https://user-images.githubusercontent.com/19530862/143512004-a8ed992f-7610-4a51-a92a-2a59549cb79e.png)
이미지 1 (2x2 픽셀)

![image](https://user-images.githubusercontent.com/19530862/143512013-3fbd73e8-544d-479b-963f-ecf352237978.png)
이미지 2 (4x4 픽셀)

![image](https://user-images.githubusercontent.com/19530862/143512024-bee6130a-288f-4f45-8b92-cc6bf4d434d9.png)
이미지 3 (8x8 픽셀)

감사합니다.

**Comment by daemyung** [comment]
이 문제는 여러가지 원인들에 의해 복합적으로 발생하는 문제입니다.

1. 3차원 위치 정보가 2차원 위치 정보로 변환될 때, 딱 맞아 떨어지지 않아 발생할 수 있습니다. 정점의 위치를 -1.0 또는 1.0으로 변경하할 수 있습니다.
2. Sampler의 Wrap 모드의 기본 설정인 GL_REPEAT에 의해 발생할 수 있습니다. GL_CLAMP_TO_EDGE 등으로 변경할 수 있습니다.
3. @sejinpark12님이 시도하신 방법으로 샘플링하기 충분한 데이터를 제공하는 방식으로 변경할 수 있습니다.

나열한 방법 외에도 다른 원인에 의해서 이러한 문제가 발생할 수 있습니다. 현업에서는 충분한 텍스쳐 크기와 밉맵을 제공하기 때문에 이러한 문제는 거의 발생하지 않습니다.

**Comment by sejinpark12** [comment]
자세한 설명 감사합니다ㅎ
강의 항상 잘 보고 있습니다.

**Comment by daemyung** [comment]
@sejinpark12 감사합니다. 제가 게을러서 강의를 빨리 못만들고 있는데, 세진님의 질문이 많이 힘이 되네요.
